name: android_build_CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 16.x
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Defold
      uses: dapetcu21/setup-defold@v3.0.2
      
    - name: Install Dependencies
      run:  npm install
      
    - name: Genrate lua w/ ts-defold
      run:  npm run build&&npm run setmain

    - name: Build
      run: 'java -jar $BOB --root ./app --archive --platform armv7-android --bundle-output ./build --verbose resolve distclean build bundle'
    - name: Archive build results
      uses: actions/upload-artifact@v4
      with:
        name: android_build
        path: ./build


